import os,json,shutil,html,urllib.parse
from pathlib import Path
R=Path(__file__).parent; D=R/'docs'; cfg=json.load(open(R/'site.config.json')); vs=json.load(open(R/'data/vehicles.json')); langs={x:json.load(open(R/f'i18n/{x}.json')) for x in ('en','ar')}; base=cfg['base_path'].rstrip('/')
# Preserve prepared assets before rebuilding pages
assetdir=D/'assets'; assetdir.mkdir(parents=True,exist_ok=True)
shutil.copy2(R/'src/css/site.css',assetdir/'site.css');shutil.copy2(R/'src/js/site.js',assetdir/'site.js')
def esc(x): return html.escape(str(x or ''),quote=True)
def route(l,s=''): return f'{base}/{l}/'+(s.strip('/')+'/' if s else '')
def asset(s): return f'{base}/assets/{s}'
def money(n,l): return f"{n:,} {'ج.م' if l=='ar' else 'EGP'}"
def vname(v): return f"{v['year']} {v['brand']} {v['model']}"
def nav(l,t,active,slug=''):
 other='en' if l=='ar' else 'ar'; page=slug if active=='car' else ('' if active=='home' else active)
 links=[('home','',t['nav']['home']),('inventory','inventory',t['nav']['inventory']),('sell','sell',t['nav']['sell']),('about','about',t['nav']['about']),('contact','contact',t['nav']['contact'])]
 return f'''<a class="skip" href="#main">{'تجاوز إلى المحتوى' if l=='ar' else 'Skip to content'}</a><header class="site-header"><div class="wrap header"><a class="brand" href="{route(l)}"><img src="{asset('brand/icon.png')}" alt="" width="44" height="44"><span><b>YOUSSEF HANY</b><small>LUXURY &amp; EXOTICS</small></span></a><nav class="nav" aria-label="{'التنقل الرئيسي' if l=='ar' else 'Main navigation'}">{''.join(f'<a href="{route(l,s)}" {"aria-current=\"page\"" if active==k else ""}>{label}</a>' for k,s,label in links)}<a class="lang" lang="{other}" href="{route(other,page)}">{t['nav']['language']}</a></nav></div></header>'''
def footer(l,t): return f'''<footer class="footer"><div class="wrap"><div class="footer-top"><div class="brand"><img src="{asset('brand/icon.png')}" alt="" width="40" height="40"><span><b>YOUSSEF HANY</b><small>LUXURY &amp; EXOTICS</small></span></div><div class="footer-links"><a href="{route(l,'privacy')}">{t['footer']['privacy']}</a><a href="{route(l,'terms')}">{t['footer']['terms']}</a><a href="{route(l,'fees-and-refunds')}">{t['footer']['fees']}</a><a href="{route(l,'cookies')}">{t['footer']['cookies']}</a><a href="{route(l,'contact')}">{t['footer']['contact']}</a></div></div><p>{t['footer']['note']}</p><p>{t['footer']['disclaimer']}</p><p>{t['pages']['credits']}</p></div></footer>'''
def shell(l,t,active,title,desc,body,slug=''):
 canonical=route(l,slug) if slug else route(l)
 other='en' if l=='ar' else 'ar'; otherurl=route(other,slug)
 return f'''<!doctype html><html lang="{l}" dir="{'rtl' if l=='ar' else 'ltr'}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="referrer" content="strict-origin-when-cross-origin"><title>{esc(title)} | Youssef Hany Luxury &amp; Exotics</title><meta name="description" content="{esc(desc)}"><link rel="canonical" href="https://youssefhany911m4.github.io{canonical}"><link rel="alternate" hreflang="{l}" href="https://youssefhany911m4.github.io{canonical}"><link rel="alternate" hreflang="{other}" href="https://youssefhany911m4.github.io{otherurl}"><link rel="alternate" hreflang="x-default" href="https://youssefhany911m4.github.io{route('en')}"><meta property="og:type" content="website"><meta property="og:title" content="{esc(title)} | Youssef Hany"><meta property="og:description" content="{esc(desc)}"><meta property="og:image" content="https://youssefhany911m4.github.io{asset('brand/primary-logo.png')}"><meta name="twitter:card" content="summary_large_image"><link rel="icon" href="{asset('brand/favicon.png')}"><link rel="apple-touch-icon" href="{asset('brand/app-icon.png')}"><link rel="stylesheet" href="{asset('site.css')}"><script defer src="{asset('site.js')}"></script></head><body>{nav(l,t,active,slug)}<main id="main">{body}</main>{footer(l,t)}</body></html>'''
def card(v,l,t):
 if v['status'] in ('hidden','sold'): return ''
 im=v['images'][0]; details=[]
 if v.get('trim'): details.append(v['trim'][l])
 if v.get('mileage_km') is not None: details.append(f"{v['mileage_km']:,} {t['car']['km']}")
 if v.get('location'): details.append(v['location'][l])
 return f'''<article class="card" data-card data-brand="{esc(v['brand'])}" data-price="{v['price']}" data-year="{v['year']}" data-status="{v['status']}" data-added="{v['added']}"><a href="{route(l,'cars/'+v['id'])}"><div class="card-img"><img src="{asset('cars/'+v['id']+'/'+im['file'])}" alt="{esc(im['alt'][l])}" width="800" height="600" loading="lazy"></div><div class="card-body"><span class="status">{t['car'].get(v['status'],t['car']['available'])}</span><h3>{esc(vname(v))}</h3><div class="price">{money(v['price'],l)}</div><div class="meta">{''.join(f'<span>{esc(x)}</span>' for x in details)}</div></div></a></article>'''
def steps(t): return '<ol class="steps">'+''.join(f'<li><span>{esc(x)}</span></li>' for x in t['home']['steps'])+'</ol>'
def home(l,t):
 featured=sorted([v for v in vs if v['status']=='available'],key=lambda v:v['price'],reverse=True)[:3]
 body=f'''<section class="hero"><div class="wrap hero-grid"><div><h1>{t['home']['title']}</h1><p>{t['home']['intro']}</p><div class="actions"><a class="button" href="{route(l,'inventory')}">{t['home']['inventory']}</a><a class="button secondary" href="{route(l,'sell')}">{t['home']['sell']}</a></div></div><img class="hero-logo" src="{asset('brand/primary-logo.png')}" alt="Youssef Hany Luxury &amp; Exotics" width="420" height="320"></div></section><section class="section"><div class="wrap"><div class="section-head"><div><h2>{t['home']['featured']}</h2><p>{t['inventory']['intro']}</p></div><a href="{route(l,'inventory')}">{t['home']['all']}</a></div><div class="grid">{''.join(card(v,l,t) for v in featured)}</div></div></section><section class="section"><div class="wrap"><h2>{t['home']['how']}</h2>{steps(t)}</div></section><section class="section"><div class="wrap"><h2>{t['home']['services']}</h2><div class="service-list"><div class="service-row"><h3>{t['home']['buy']}</h3><p>{t['home']['buyText']}</p><a href="{route(l,'inventory')}">{t['home']['inventory']} →</a></div><div class="service-row"><h3>{t['nav']['sell']}</h3><p>{t['home']['sellText']}</p><a href="{route(l,'sell')}">{t['nav']['sell']} →</a></div><div class="service-row"><h3>{t['home']['find']}</h3><p>{t['home']['findText']}</p><a href="{route(l,'find-a-car')}">{t['home']['find']} →</a></div></div></div></section><section class="section"><div class="wrap"><div class="commission"><h2>{t['home']['commission']}</h2><p>{t['home']['commissionText']}</p><a href="{route(l,'fees-and-refunds')}">{t['pages']['fees']} →</a></div></div></section>'''
 return shell(l,t,'home',t['home']['title'],t['home']['intro'],body)
def inventory(l,t):
 brands=sorted(set(v['brand'] for v in vs)); years=sorted(set(v['year'] for v in vs),reverse=True)
 body=f'''<div class="wrap"><section class="intro"><h1>{t['inventory']['title']}</h1><p>{t['inventory']['intro']}</p></section><div class="filters" data-filters><div><label for="q">{t['inventory']['search']}</label><input id="q" name="q" type="search" placeholder="{t['inventory']['search']}"></div><div><label for="brand">{t['inventory']['brand']}</label><select id="brand" name="brand"><option value="">{t['inventory']['all']}</option>{''.join(f'<option>{esc(b)}</option>' for b in brands)}</select></div><div><label for="year">{t['inventory']['year']}</label><select id="year" name="year"><option value="">{t['inventory']['all']}</option>{''.join(f'<option>{y}</option>' for y in years)}</select></div><div><label for="status">{t['inventory']['availability']}</label><select id="status" name="status"><option value="">{t['inventory']['all']}</option><option value="available">{t['inventory']['available']}</option><option value="reserved">{t['inventory']['reserved']}</option><option value="sold">{t['inventory']['sold']}</option></select></div><div><label for="minprice">{t['inventory']['priceLow']}</label><input id="minprice" name="minprice" type="number" min="0" inputmode="numeric" aria-label="Minimum price"></div><div><label for="sort">{t['inventory']['sort']}</label><select id="sort" name="sort"><option value="desc">{t['inventory']['priceHigh']}</option><option value="asc">{t['inventory']['priceLow']}</option><option value="year">{t['inventory']['yearNew']}</option><option value="added">{t['inventory']['newest']}</option></select></div></div><p class="small" data-count aria-live="polite"></p><div class="grid">{''.join(card(v,l,t) for v in vs)}</div><div class="empty" data-empty hidden><p>{t['inventory']['empty']}</p><a class="button" href="{route(l,'find-a-car')}">{t['inventory']['find']}</a></div></div>'''
 return shell(l,t,'inventory',t['inventory']['title'],t['inventory']['intro'],body,'inventory')
def detail(v,l,t):
 ims=v['images']; im=ims[0]; rows=[]
 for key,label,value in [('trim',t['car']['trim'],v.get('trim',{}).get(l) if v.get('trim') else None),('spec',t['car']['spec'],t['car']['fully'] if v.get('spec') else None),('body',t['car']['body'],v.get('body')),('condition',t['car']['condition'],v.get('condition',{}).get(l) if v.get('condition') else None),('mileage_km',t['car']['mileage'],f"{v['mileage_km']:,} {t['car']['km']}" if v.get('mileage_km') is not None else None),('location',t['car']['location'],v.get('location',{}).get(l) if v.get('location') else None)]:
  if value: rows.append((label,value))
 msg=(f"مرحباً يوسف هاني، أنا مهتم بسيارة {v['brand']} {v['model']} موديل {v['year']}"+(f"، {v['trim']['ar']}" if v.get('trim') else '')+f" المعروضة بسعر {v['price']:,} جنيه. هل ما زالت متاحة?") if l=='ar' else f"Hello Youssef Hany, I am interested in the {v['year']} {v['brand']} {v['model']}{', '+v['trim']['en'] if v.get('trim') else ''}, listed at EGP {v['price']:,}. Is it still available?"
 wa='https://wa.me/'+cfg['whatsapp_number']+'?text='+urllib.parse.quote(msg)
 body=f'''<div class="wrap"><section class="detail"><div><img class="main-photo" data-main src="{asset('cars/'+v['id']+'/'+im['file'])}" alt="{esc(im['alt'][l])}" width="1280" height="960"><div class="thumbs" aria-label="{'صور السيارة' if l=='ar' else 'Vehicle photos'}">{''.join(f'<button type="button" data-thumb="{asset("cars/"+v["id"]+"/"+x["file"])}" data-alt="{esc(x["alt"][l])}" aria-label="Photo {i+1}"><img src="{asset("cars/"+v["id"]+"/"+x["file"])}" alt="" loading="lazy"></button>' for i,x in enumerate(ims))}</div></div><div class="detail-info"><p class="status">{t['car'].get(v['status'],t['car']['available'])}</p><h1>{esc(vname(v))}</h1><div class="price">{money(v['price'],l)}</div><p class="small">{t['car']['priceNote']}</p><div class="specs">{''.join(f'<div class="spec"><span>{esc(a)}</span><span>{esc(b)}</span></div>' for a,b in rows)}</div><div class="actions"><a class="button" href="{wa}" target="_blank" rel="noopener noreferrer">{t['car']['ask']}</a><a class="button secondary" href="tel:+201014437631">{t['car']['call']}</a><button type="button" class="secondary" data-share>{t['car']['share']}</button></div><p class="small"><a href="{route(l,'privacy')}">{t['pages']['privacy']}</a></p></div></section></div>'''
 return shell(l,t,'car',vname(v),f"{vname(v)}. {money(v['price'],l)}.",body,'cars/'+v['id'])
def formpage(l,t,kind):
 f=t['forms']; sell=kind=='sell'; title=f['sellTitle'] if sell else f['findTitle']; desc=f['sellIntro'] if sell else f['findIntro']; fields=[('brand',f['brand'],1,'text'),('model',f['model'],1,'text'),('year',f['year'],1,'number'),('mileage',f['mileage'],1,'number'),('price',f['price'],0,'number'),('city',f['city'],0,'text'),('notes',f['notes'],0,'textarea'),('first',f['first'],0,'text')] if sell else [('brand',f['brand'],1,'text'),('model',f['model'],1,'text'),('yearFrom',f['yearFrom'],0,'number'),('yearTo',f['yearTo'],0,'number'),('budget',f['budget'],0,'number'),('notes',f['notes'],0,'textarea')]
 controls=''.join(f'<div class="field"><label for="{key}">{label}{" *" if req else ""}</label>{f"<textarea id='{key}' name='{key}' {'required' if req else ''}></textarea>" if typ=="textarea" else f"<input id='{key}' name='{key}' type='{typ}' {'inputmode=\"numeric\" min=\"0\"' if typ=='number' else ''} {'required' if req else ''}>"}</div>' for key,label,req,typ in fields)
 consent=f['consent'].replace('Privacy Policy',f'<a href="{route(l,"privacy")}">{t["pages"]["privacy"]}</a>').replace('سياسة الخصوصية',f'<a href="{route(l,"privacy")}">سياسة الخصوصية</a>')
 body=f'''<div class="wrap"><section class="intro"><h1>{title}</h1><p>{desc}</p></section><form class="form" data-form data-kind="{'sell' if sell else 'find'}" novalidate>{controls}<div class="consent"><input type="checkbox" id="consent" name="consent"><label for="consent">{consent}</label></div><p class="error" data-error role="status" tabindex="-1" hidden>{f['required']}</p><p class="small">{f['age']}</p><p class="small">{f['photos']}</p><p class="small">{f['whatsappNote']}</p><button type="submit">{f['submit']}</button></form></div>'''
 return shell(l,t,'sell' if sell else 'find-a-car',title,desc,body,'sell' if sell else 'find-a-car')
def textpage(l,t,slug):
 p=t['pages'];title=p.get(slug.replace('-and-refunds',''),p['about']); content=''
 if slug=='about': content=f"<p>{p['aboutText']}</p><h2>{p['process']}</h2>{steps(t)}<h2>{p['commission']}</h2><p>{t['home']['commissionText']}</p><h2>{p['faq']}</h2><details><summary>{p['faq1']}</summary><p>{p['faq1a']}</p></details><details><summary>{p['faq2']}</summary><p>{p['faq2a']}</p></details><details><summary>{p['faq3']}</summary><p>{p['faq3a']}</p></details>"
 elif slug=='contact':
  title=p['contact'];content=f"<p>{p['contactText']}</p><ul class='contact-list'><li><span>WhatsApp / Phone</span><a dir='ltr' target='_blank' rel='noopener noreferrer' href='https://wa.me/{cfg['whatsapp_number']}'>{cfg['phone_display']}</a></li><li><span>Email</span><a href='mailto:{cfg['email']}'>{cfg['email']}</a></li><li><span>Instagram</span><a target='_blank' rel='noopener noreferrer' href='{cfg['instagram']}'>@youssefhany911m4</a></li><li><span>Facebook</span><a target='_blank' rel='noopener noreferrer' href='{cfg['facebook']}'>Facebook</a></li></ul><p class='notice'>{p['legalDraft']}</p>"
 elif slug=='privacy':
  title=p['privacy'];content=f"<p class='notice'>{p['legalDraft']}</p><p>{p['privacyText']}</p><h2>{'البيانات والحقوق' if l=='ar' else 'Data and rights'}</h2><p>{'قد تتضمن البيانات التي تختار إرسالها عبر WhatsApp تفاصيل السيارة والرسالة والاسم الأول الاختياري. يجب على المالك تحديد مدة الاحتفاظ بالمحادثات ومن يمكنه الوصول إليها ووقت الرد على طلبات الحذف.' if l=='ar' else 'Data you choose to send through WhatsApp may include vehicle details, your message and an optional first name. The owner must specify chat retention, access, and response times for deletion requests.'}</p><p>{'لن تُضاف جهات الاتصال إلى قوائم البث دون سؤال مسبق. يمكنك طلب إيقاف التواصل بقول «توقف».' if l=='ar' else 'Contacts will not be added to broadcast lists without asking first. You can ask for contact to stop by saying “stop”.'}</p>"
 elif slug=='terms':
  title=p['terms'];content=f"<p class='notice'>{p['legalDraft']}</p><p>{p['termsText']}</p><h2>{'القانون والاختصاص' if l=='ar' else 'Governing law and jurisdiction'}</h2><p>{'يجب استكمال القانون والاختصاص من المالك ومحامٍ مؤهل قبل النشر.' if l=='ar' else 'Governing law and jurisdiction must be completed by the owner and qualified counsel before publication.'}</p>"
 elif slug=='fees-and-refunds':
  title=p['fees'];content=f"<p class='notice'>{p['legalDraft']}</p><p>{p['feesText']}</p><p>{'يجب تأكيد من يدفع العمولة وأساس حسابها وموعد استحقاقها والضرائب أو الرسوم الإضافية وما إذا كان يتم أخذ أي عربون وشروط استرداده.' if l=='ar' else 'The commission payer, calculation basis, due date, taxes or charges, and deposit/refund terms must be confirmed before launch.'}</p>"
 else: title=p['cookies'];content=f"<p class='notice'>{p['legalDraft']}</p><p>{p['cookiesText']}</p>"
 body=f'<div class="wrap"><section class="intro"><h1>{title}</h1></section><article class="text-page">{content}</article></div>'
 return shell(l,t,slug,title,p['legalDraft'],body,slug)
# rebuild pages, preserve assets
for l,t in langs.items():
 pages={'':home(l,t),'inventory':inventory(l,t),'sell':formpage(l,t,'sell'),'find-a-car':formpage(l,t,'find')}
 for slug in ['about','contact','privacy','terms','fees-and-refunds','cookies']: pages[slug]=textpage(l,t,slug)
 for v in vs: pages['cars/'+v['id']]=detail(v,l,t)
 for slug,doc in pages.items():
  dest=D/l/(slug if slug else '')/'index.html';dest.parent.mkdir(parents=True,exist_ok=True);dest.write_text(doc,encoding='utf-8')
D.joinpath('index.html').write_text(f'''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="refresh" content="0; url={route('en')}"><title>Youssef Hany | Luxury &amp; Exotics</title><script>try{{let l=localStorage.getItem('yh-language');if(l!=='ar'&&l!=='en')l=(navigator.language||'').toLowerCase().startsWith('ar')?'ar':'en';location.replace('{base}/'+l+'/')}}catch(e){{location.replace('{route('en')}')}}</script><body><a href="{route('ar')}">العربية</a> · <a href="{route('en')}">English</a></body></html>''',encoding='utf-8')
D.joinpath('404.html').write_text(f'<!doctype html><html lang="en"><meta charset="utf-8"><link rel="stylesheet" href="{asset("site.css")}"><body class="wrap section"><h1>Page not found</h1><a class="button" href="{route("en")}">Return home</a></body></html>',encoding='utf-8')
urls=[]
for l in langs:
 for slug in ['', 'inventory','sell','find-a-car','about','contact','privacy','terms','fees-and-refunds','cookies']+['cars/'+v['id'] for v in vs]: urls.append(f'<url><loc>https://youssefhany911m4.github.io{route(l,slug)}</loc><lastmod>2026-10-09</lastmod></url>')
D.joinpath('sitemap.xml').write_text('<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+''.join(urls)+'</urlset>')
D.joinpath('robots.txt').write_text('User-agent: *\nAllow: /\nSitemap: https://youssefhany911m4.github.io'+base+'/sitemap.xml\n')
D.joinpath('manifest.webmanifest').write_text(json.dumps({'name':'Youssef Hany Luxury & Exotics','short_name':'YH Luxury','start_url':route('en'),'display':'standalone','background_color':'#0b0b0a','theme_color':'#0b0b0a','icons':[{'src':asset('brand/app-icon.png'),'sizes':'512x512','type':'image/png'}]},indent=2))
print('Generated bilingual static site.')
